name: Test, Build & Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [14.x, 16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: | 
          npm install
          npm run test

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Node Express TypeScript BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or Public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of server you want to ssh into
          
          script: |
            cd /var/www/unsplash.juggyprojects.com/
            rm -r Dev-Challenges-Unsplash-Express-BE
            git clone git@github.com:JUGG097/Dev-Challenges-Unsplash-Express-BE.git
            cd Dev-Challenges-Unsplash-Express-BE
            cp /var/www/unsplash.juggyprojects.com/.env /var/www/unsplash.juggyprojects.com/Dev-Challenges-Unsplash-Express-BE/.env
            npm install
            npx tsc
            pm2 stop unsplashExpressBE
            pm2 start dist/index.js --name unsplashExpressBE
            echo 'Deployment Successful To Digital Ocean'